import type { Metadata } from "next";
import "./globals.css";

import { Rajdhani, Raleway } from "next/font/google";
import Header from "@/components/header/page";
import FooterPage from "@/components/Footer/page";
import MobileBottomNav from "@/components/Tab/page";
import ReduxProvider from "@/redux/provider";
import { getAllCategories } from "@/lib/data/category";

const rajdhani = Rajdhani({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
  variable: "--font-rajdhani",
});

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
});

export const metadata: Metadata = {
  title: "Liana",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  const allCategories = await getAllCategories();
  console.log(allCategories);
  return (
    <html lang="en">
      <body
        className={`${rajdhani.variable} ${raleway.variable} bg-white scroll-smooth`}
        cz-shortcut-listen="true"
      >
        <main>
          <ReduxProvider>
            <Header categories ={allCategories}/>
            <MobileBottomNav />
            {children}
            <FooterPage />
          </ReduxProvider>
        </main>
      </body>
    </html>
  );
}
